### ISSUE TITLE
hi: I have questions for CortanaIntelligenceSuiteWorkshopManual/05_Exercise_5_-_Summarize_Data_Using_HDInsight_Spark.md

### ISSUE THREAD

**Issue by boulegit** [toddkitta/CortanaIntelligenceSuiteWorkshopManual#21]
In the Task1:
I Copy the below text and paste it into the Jupyter notebook.
But it is error.
cloud you help me. how to solve it.
thank you

I use below code:
import sqlContext.implicits._

val flightDelayTextLines = sc.textFile("wasb:///Scored_FlightsAndWeather.csv")

case class AirportFlightDelays(OriginAirportCode:String,OriginLatLong:String,Month:Integer,Day:Integer,Hour:Integer,Carrier:String,DelayPredicted:Integer,DelayProbability:Double)

val flightDelayRowsWithoutHeader = flightDelayTextLines.map(s => s.split(",")).filter(line => line(0) != "OriginAirportCode")

val resultDataFrame = flightDelayRowsWithoutHeader.map(
    s => AirportFlightDelays(
        s(0), //Airport code
        s(13) + "," + s(14), //Lat,Long
        s(1).toInt, //Month
        s(2).toInt, //Day
        s(3).toInt, //Hour
        s(5), //Carrier
        s(11).toInt, //DelayPredicted
        s(12).toDouble //DelayProbability
        )
).toDF()

resultDataFrame.write.mode("overwrite").saveAsTable("FlightDelays")

_****but it is error****_ 
`Creating HiveContext as 'sqlContext'
SparkContext and HiveContext created. Executing user code ...
org.apache.spark.SparkException: Job aborted.
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelation$$anonfun$run$1.apply$mcV$sp(InsertIntoHadoopFsRelation.scala:154)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelation$$anonfun$run$1.apply(InsertIntoHadoopFsRelation.scala:106)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelation$$anonfun$run$1.apply(InsertIntoHadoopFsRelation.scala:106)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:56)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelation.run(InsertIntoHadoopFsRelation.scala:106)
	at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult$lzycompute(commands.scala:58)
	at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult(commands.scala:56)
	at org.apache.spark.sql.execution.ExecutedCommand.doExecute(commands.scala:70)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:132)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:130)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:130)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:55)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:55)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:256)
	at org.apache.spark.sql.hive.execution.CreateMetastoreDataSourceAsSelect.run(commands.scala:274)
	at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult$lzycompute(commands.scala:58)
	at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult(commands.scala:56)
	at org.apache.spark.sql.execution.ExecutedCommand.doExecute(commands.scala:70)`

**Comment by MarPyk** [comment]
Hi,
I've similar error like this.
Have You got any solution?
BR,
Marek

**Comment by kushagara175** [comment]
The error message you provided indicates that there was a problem when writing the data to the Hive table "FlightDelays". It seems that the job was aborted during this process.

One possible cause of this error is that there is already a table with the same name in the Hive metastore. You can try dropping the existing table before creating a new one using the following command:

arduino
Copy code
sqlContext.sql("DROP TABLE IF EXISTS FlightDelays")
Another possible cause of this error is related to the format of the data being written to the table. Make sure that the schema of your data matches the schema of the table you are trying to write to.

You can also try increasing the memory and/or number of executor cores in your Spark configuration to see if that helps.

Finally, make sure that you have the necessary permissions to write to the Hive table.
